kind: pipeline
type: docker
name: dirl

steps:
- name: publish-container
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    dockerfile: Dockerfile
    purge: true
    repo: arminfriedl/lukewarm
    tags: latest
